# Generated by Django 3.2.4 on 2022-02-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=500)),
                ('tecnologia', models.CharField(max_length=500)),
                ('terminadado', models.BooleanField()),
                ('fecha_estimada', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Resgistro',
        ),
    ]
