# Generated by Django 3.2.4 on 2022-02-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20220211_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
