# Generated by Django 3.2.4 on 2022-02-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_recomendaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='detallles',
            new_name='detalles',
        ),
    ]
